const actionTypes = {
  SET_USER: "SET_USER",
  SET_TASKS: "SET_TASKS",
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  EDIT_TASK: "EDIT_TASK",
  SELECT_TASK_TO_EDIT: "SELECT_TASK_TO_EDIT",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
};

export default actionTypes;
